# GitHub Secret Scanning Configuration
# This file tells GitHub that certain patterns are safe to ignore

# Firebase API keys are public by design
# See: https://firebase.google.com/docs/projects/api-keys#api-keys-for-firebase-are-different
